#ifndef COMMUNICATION_H
#define COMMUNICATION_H

#define PORT 8080
#define SERVER_IP "127.0.0.1"
#define MAX_MSG 512

// JSON mesaj tipleri
#define MSG_STATUS_UPDATE "STATUS_UPDATE"
#define MSG_ASSIGN_MISSION "ASSIGN_MISSION"
#define MSG_MISSION_COMPLETE "MISSION_COMPLETE"

#endif
